import { Event } from "./types";

let nextId = 1;
function id() {
  return String(nextId++);
}

export const sampleEvent: Event = {
  coupleName: "Alex Morgan & Jordan Reyes",
  date: "Saturday, October 17, 2026",
  venue: "The Heritage Pavilion",
  guestCounts: [
    { label: "Wedding", count: 137 },
    { label: "Rehearsal Dinner", count: 15 },
    { label: "Welcome Party", count: 109 },
  ],
  attire: [
    { occasion: "Wedding", dress: "Black Tie" },
    { occasion: "Rehearsal Dinner", dress: "Semi Formal" },
  ],
  parties: [
    {
      initials: "LP",
      name: "Lead Planner",
      role: "Lead Planner",
      category: "PLANNING_TEAM",
      email: "lead@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "AP",
      name: "Asst Planner",
      role: "Senior Coordinator",
      category: "PLANNING_TEAM",
      email: "coordinator@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "C1",
      name: "Coordinator 1",
      role: "Coordinator",
      category: "PLANNING_TEAM",
      email: "coord1@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "C2",
      name: "Coordinator 2",
      role: "Coordinator",
      category: "PLANNING_TEAM",
      email: "coord2@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "A1",
      name: "Assistant 1",
      role: "Assistant",
      category: "PLANNING_TEAM",
      email: "asst1@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "A2",
      name: "Assistant 2",
      role: "Assistant",
      category: "PLANNING_TEAM",
      email: "asst2@sampleevents.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "FL",
      name: "Floral Lead",
      role: "Floral Design",
      category: "VENDOR",
      email: "floral@vendor.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "PH",
      name: "Photo Lead",
      role: "Photographer",
      category: "VENDOR",
      email: "photo@vendor.demo",
      phone: "555.100.2001",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "EN",
      name: "Entertainment Lead",
      role: "Entertainment",
      category: "VENDOR",
      email: "entertainment@vendor.demo",
      phone: "555.100.2002",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "HA",
      name: "Hair Stylist",
      role: "Hair",
      category: "VENDOR",
      email: "hair@vendor.demo",
      phone: "555.100.2003",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "MU",
      name: "Makeup Artist",
      role: "Makeup Artist",
      category: "VENDOR",
      email: "makeup@vendor.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "VD",
      name: "Video Lead",
      role: "Videographer",
      category: "VENDOR",
      email: "video@vendor.demo",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
    {
      initials: "RN",
      name: "Rentals Company",
      role: "Rentals",
      category: "VENDOR",
      scope: { preEvent: true, duringEvent: false, postEvent: true },
    },
    {
      initials: "CK",
      name: "Cake Artisan",
      role: "Cake",
      category: "VENDOR",
      scope: { preEvent: true, duringEvent: false, postEvent: true },
    },
    {
      initials: "VN",
      name: "The Heritage Pavilion",
      role: "Venue",
      category: "VENUE",
      scope: { preEvent: true, duringEvent: true, postEvent: true },
    },
  ],
  days: [
    {
      label: "Friday, October 16 — Rehearsal & Welcome",
      sections: [
        {
          title: "REHEARSAL & WELCOME PARTY",
          items: [
            {
              id: id(),
              time: "3:00 PM",
              initials: ["LP", "AP"],
              description: "Planning team arrives at Heritage Pavilion for rehearsal walk-through",
              subNote: "Meet at lobby; confirm ceremony space setup",
            },
            {
              id: id(),
              time: "4:00 PM",
              initials: ["ALL"],
              description: "Wedding rehearsal begins",
              subNote: "Run full ceremony sequence with officiant",
              isBold: true,
            },
            {
              id: id(),
              time: "5:00 PM",
              initials: ["LP"],
              description: "Rehearsal concludes — transition to welcome party",
            },
            {
              id: id(),
              time: "6:30 PM",
              initials: ["ALL"],
              description: "Welcome party begins",
              subNote: "109 guests; cocktail attire",
              isBold: true,
            },
            {
              id: id(),
              time: "9:00 PM",
              initials: ["LP", "AP"],
              description: "Welcome party concludes",
            },
          ],
        },
      ],
    },
    {
      label: "Saturday, October 17 — Wedding Day",
      sections: [
        {
          title: "VENDOR SETUP & PREPARATION",
          items: [
            {
              id: id(),
              time: "5:00 AM",
              initials: ["FL"],
              description: "Floral team load-in begins",
              subNote: "Service entrance; coordinate with venue loading dock",
            },
            {
              id: id(),
              time: "6:00 AM",
              initials: ["RN"],
              description: "Rentals delivery and setup",
              subNote: "Linens, chargers, specialty furniture — ceremony + reception",
            },
            {
              id: id(),
              time: "7:00 AM",
              initials: ["CK"],
              description: "Cake delivery and assembly",
              subNote: "Five-tier; coordinate with catering for display table",
            },
            {
              id: id(),
              time: "7:30 AM",
              initials: ["LP", "AP", "C1", "C2", "A1", "A2"],
              description: "Full planning team arrives on site",
              subNote: "Team briefing in planning suite; review day-of timeline",
              isBold: true,
            },
            {
              id: id(),
              time: "8:00 AM",
              initials: ["C1", "A1"],
              description: "Begin ceremony space setup oversight",
              subNote: "Confirm aisle width, chair placement, florals",
            },
            {
              id: id(),
              time: "8:30 AM",
              initials: ["AP", "A2"],
              description: "Reception room setup oversight",
              subNote: "Table numbers, place cards, favors, menus",
            },
          ],
        },
        {
          title: "HAIR & MAKEUP",
          items: [
            {
              id: id(),
              time: "9:00 AM",
              initials: ["HA", "MU"],
              description: "Hair and makeup team arrives at bridal suite",
              subNote: "Setup in Heritage Pavilion bridal suite",
            },
            {
              id: id(),
              time: "9:45 AM",
              initials: ["HA", "MU"],
              description: "Bridal party hair and makeup begins",
              subNote: "Bride scheduled last for freshest look; 6 attendants",
              isBold: true,
            },
            {
              id: id(),
              time: "12:30 PM",
              initials: ["HA", "MU"],
              description: "Bride hair and makeup begins",
              subNote: "Allow 2 hours; trial look confirmed",
            },
          ],
        },
        {
          title: "PHOTOGRAPHY & FIRST LOOK",
          items: [
            {
              id: id(),
              time: "1:30 PM",
              initials: ["PH", "VD"],
              description: "Photo and video teams arrive",
              subNote: "Gear setup in suite; review shot list with Lead Planner",
              isBold: true,
            },
            {
              id: id(),
              time: "2:00 PM",
              initials: ["PH"],
              description: "Detail shots — rings, invitation suite, shoes, dress",
              subNote: "Flat lay station set up in parlor room",
            },
            {
              id: id(),
              time: "2:30 PM",
              initials: ["PH", "VD"],
              description: "Bride getting-ready coverage begins",
            },
            {
              id: id(),
              time: "3:00 PM",
              initials: ["PH"],
              description: "Groom and groomsmen portraits",
              subNote: "Lounge area — reserve corner seating",
            },
            {
              id: id(),
              time: "4:00 PM",
              initials: ["PH", "VD", "LP"],
              description: "First look",
              subNote: "Garden terrace — private, Lead Planner to clear space",
              isBold: true,
            },
            {
              id: id(),
              time: "4:15 PM",
              initials: ["PH"],
              description: "Couple portraits following first look",
              subNote: "30 minutes; outdoor garden if weather permits",
            },
            {
              id: id(),
              time: "4:45 PM",
              initials: ["PH"],
              description: "Wedding party group photos",
              subNote: "Grand staircase — 15 combinations per shot list",
            },
          ],
        },
        {
          title: "CEREMONY",
          items: [
            {
              id: id(),
              time: "5:00 PM",
              initials: ["C1", "C2"],
              description: "Guest shuttle buses depart from hotel block",
              subNote: "Three buses; confirm headcount with concierge by 4 PM",
              isBold: true,
            },
            {
              id: id(),
              time: "5:15 PM",
              initials: ["A1", "A2"],
              description: "Ceremony doors open — guests begin seating",
              subNote: "Programs distributed; ushers guide to assigned sections",
            },
            {
              id: id(),
              time: "5:45 PM",
              initials: ["LP"],
              description: "Bridal party lineup in holding room",
              subNote: "Final touch-ups; bouquets distributed; mic check officiant",
            },
            {
              id: id(),
              time: "6:00 PM",
              initials: ["ALL"],
              description: "Ceremony begins",
              subNote: "Processional order confirmed at rehearsal; string quartet cue",
              isBold: true,
            },
            {
              id: id(),
              time: "6:30 PM",
              initials: ["ALL"],
              description: "Ceremony concludes — cocktail hour begins",
              subNote: "Recessional; guests directed to Grand Ballroom foyer",
              isBold: true,
            },
          ],
        },
        {
          title: "COCKTAIL HOUR & RECEPTION",
          items: [
            {
              id: id(),
              time: "6:30 PM",
              initials: ["AP", "C1"],
              description: "Cocktail hour — passed hors d'oeuvres and bar service",
              subNote: "Specialty cocktails: Signature One and Signature Two",
            },
            {
              id: id(),
              time: "7:00 PM",
              initials: ["LP", "AP"],
              description: "Ceremony space flip to late-night lounge",
              subNote: "Coordinate with rentals team; 45-minute window",
            },
            {
              id: id(),
              time: "7:30 PM",
              initials: ["LP"],
              description: "Final reception room check",
              subNote: "Lighting, candles, place cards, centerpiece alignment",
            },
            {
              id: id(),
              time: "7:45 PM",
              initials: ["EN"],
              description: "Band on stage — sound check complete",
              subNote: "12-piece ensemble; stage plot confirmed",
              isBold: true,
            },
            {
              id: id(),
              time: "8:00 PM",
              initials: ["ALL"],
              description: "Grand introduction and first dance",
              subNote: "MC announces couple; first dance song: TBD",
              isBold: true,
            },
            {
              id: id(),
              time: "8:10 PM",
              initials: ["ALL"],
              description: "Welcome toast — father of the bride",
            },
            {
              id: id(),
              time: "8:20 PM",
              initials: ["ALL"],
              description: "Dinner service begins — first course",
              subNote: "Three-course plated; dietary cards at each setting",
            },
            {
              id: id(),
              time: "8:25 PM",
              initials: ["ALL"],
              description: "Cake cutting",
              subNote: "Between first and second course; photo moment",
              isBold: true,
            },
            {
              id: id(),
              time: "9:00 PM",
              initials: ["EN"],
              description: "Band resumes — dance floor opens",
              subNote: "High-energy set",
            },
            {
              id: id(),
              time: "9:20 PM",
              initials: ["ALL"],
              description: "Father/daughter and mother/son dances",
              isBold: true,
            },
            {
              id: id(),
              time: "10:00 PM",
              initials: ["AP", "A1"],
              description: "Late-night bites station opens",
              subNote: "Sliders, fries, mini milkshakes",
            },
            {
              id: id(),
              time: "10:30 PM",
              initials: ["LP"],
              description: "Last call announcement from band",
            },
            {
              id: id(),
              time: "11:00 PM",
              initials: ["EN"],
              description: "Band final song",
              subNote: "Pre-selected closer; confetti drop on last note",
            },
            {
              id: id(),
              time: "11:15 PM",
              initials: ["LP", "AP", "C1"],
              description: "Guests directed to sendoff formation",
              subNote: "Sparkler distribution; safety briefing",
            },
            {
              id: id(),
              time: "11:30 PM",
              initials: ["ALL"],
              description: "Grand sparkler sendoff",
              subNote: "Couple departs; photo/video capture exit",
              isBold: true,
            },
          ],
        },
      ],
    },
  ],
};
